######################################################################
#
# File name : pcpu_top_tb_wave.do
# Created on: Fri Dec 17 15:18:16 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
