######################################################################
#
# File name : pcpu_top_tb.udo
# Created on: Sun Nov 28 16:29:59 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
